services:
  app:
    image: hoppscotch/hoppscotch
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      # - "3000:3000"
      # - "3100:3100"
      # - "3170:3170"
      - "80:80"
    entrypoint: >
      sh -c "
      pnpx prisma migrate deploy &&
      node /usr/src/app/aio_run.mjs
      "
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80'
      interval: 2s
      timeout: 10s
      retries: 30
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-hoppscotch}
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-testpass}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      # - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
